"""Update table

Revision ID: 7e63e04b9732
Revises: 7e06002456da
Create Date: 2025-10-16 06:21:32.405400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e63e04b9732'
down_revision: Union[str, Sequence[str], None] = '7e06002456da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crops_listings', sa.Column('status', sa.Enum('Available', 'Sold', 'Pending', name='crop_status'), nullable=False))
    op.add_column('userslist', sa.Column('role', sa.Enum('farmer', 'buyer', name='userrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userslist', 'role')
    op.drop_column('crops_listings', 'status')
    # ### end Alembic commands ###
