"""Remove status column and sync models

Revision ID: bd72d2d52705
Revises: a63d49484593
Create Date: 2025-10-16 06:55:52.346090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd72d2d52705'
down_revision: Union[str, Sequence[str], None] = 'a63d49484593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userslist', sa.Column('role', sa.Enum('farmer', 'buyer', name='userrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userslist', 'role')
    # ### end Alembic commands ###
