"""add farmer_id to crop_listings

Revision ID: ce3dc0ff600b
Revises: 
Create Date: 2026-01-31 14:52:48.486945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce3dc0ff600b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop_listings', sa.Column('farmer_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_crop_seller_id'), table_name='crop_listings')
    op.create_index('idx_crop_category_status', 'crop_listings', ['category', 'status'], unique=False)
    op.create_index(op.f('ix_crop_listings_status'), 'crop_listings', ['status'], unique=False)
    op.create_unique_constraint(None, 'crop_listings', ['id'])
    op.drop_constraint(op.f('fk_crop_seller'), 'crop_listings', type_='foreignkey')
    op.create_foreign_key(None, 'crop_listings', 'users', ['farmer_id'], ['id'])
    op.drop_column('crop_listings', 'seller_id')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_unique_constraint(None, 'users', ['phone'])
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('crop_listings', sa.Column('seller_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'crop_listings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_crop_seller'), 'crop_listings', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'crop_listings', type_='unique')
    op.drop_index(op.f('ix_crop_listings_status'), table_name='crop_listings')
    op.drop_index('idx_crop_category_status', table_name='crop_listings')
    op.create_index(op.f('idx_crop_seller_id'), 'crop_listings', ['seller_id'], unique=False)
    op.drop_column('crop_listings', 'farmer_id')
    # ### end Alembic commands ###
