"""Updated Enums Crops Category

Revision ID: cf3d3e95b76e
Revises: ce3dc0ff600b
Create Date: 2026-02-01 10:13:58.897940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf3d3e95b76e'
down_revision: Union[str, Sequence[str], None] = 'ce3dc0ff600b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_crop_category_status', 'crop_listings', ['category', 'status'], unique=False)
    op.create_index(op.f('ix_crop_listings_status'), 'crop_listings', ['status'], unique=False)
    op.create_unique_constraint(None, 'crop_listings', ['id'])
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_unique_constraint(None, 'users', ['phone'])
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'crop_listings', type_='unique')
    op.drop_index(op.f('ix_crop_listings_status'), table_name='crop_listings')
    op.drop_index('idx_crop_category_status', table_name='crop_listings')
    # ### end Alembic commands ###
