"""update crop-user relation

Revision ID: d1ea0b2836e9
Revises: 81038588e2d2
Create Date: 2026-02-01 18:59:19.662819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1ea0b2836e9'
down_revision: Union[str, Sequence[str], None] = '81038588e2d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('crop_requests')
    op.create_index('idx_crop_category_status', 'crop_listings', ['category', 'status'], unique=False)
    op.create_index(op.f('ix_crop_listings_status'), 'crop_listings', ['status'], unique=False)
    op.create_unique_constraint(None, 'crop_listings', ['id'])
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_unique_constraint(None, 'users', ['phone'])
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'crop_listings', type_='unique')
    op.drop_index(op.f('ix_crop_listings_status'), table_name='crop_listings')
    op.drop_index('idx_crop_category_status', table_name='crop_listings')
    op.create_table('crop_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('crop_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('requested_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('farmer_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('counter_offer_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('final_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('responded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop_listings.id'], name='crop_requests_crop_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='crop_requests_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('crop_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('price_per_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('delivery_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('delivery_phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('delivery_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop_listings.id'], name=op.f('orders_crop_id_fkey')),
    sa.ForeignKeyConstraint(['request_id'], ['crop_requests.id'], name=op.f('orders_request_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    # ### end Alembic commands ###
